### ISSUE TITLE
I can't even run this project...

### ISSUE THREAD

**Issue by imliuyzh** [razvanstatescu/mask-detection-ml#2]
When I downloaded the whole repository and ran it locally, I got this error...

![2020-09-10 10-01-36屏幕截图](https://user-images.githubusercontent.com/50005255/92768271-b94b3800-f34c-11ea-82a1-12e6c93873b9.png)

**Comment by ahmedch1** [comment]
Same problem here, did you get the solution?

**Comment by razvanstatescu** [comment]
This should be fixed now. I tested both on Chrome and Safari. Make sure you use a web server when running it.

**Comment by imliuyzh** [comment]
> Same problem here, did you get the solution?

I gave up using this tutorial for my project. I just used another person's instead. The code won't work even when I used a web server.

**Comment by ahmedch1** [comment]
@razvanstatescu  thanks it works , I have used xampp (I am using Windows 10)

**Comment by ahmedch1** [comment]
> > Same problem here, did you get the solution?
> 
> I gave up using this tutorial for my project. I just used another person's instead. The code won't work even when I used a web server.

What is your OS?
What is the web server used?

**Comment by imliuyzh** [comment]
@ahmedch1 
I used Win7 at that time with Python3 http.server module. I don't think this matters since I already created my own version in my profile.

**Comment by ahmedch1** [comment]
> @ahmedch1
> I used Win7 at that time with Python3 http.server module. I don't think this matters since I already created my own version in my profile.

I am using Python2 , try uninstalling Python 3 and installing Python 2 and check whether it works.
Tell me after
